Dev lh
laurelherting/portfolio pull request #104
Opened 2017-12-08 23:22 UTC by laurelherting

2017-12-10 19:37 UTC, evanharmon commented
In `public.html` you can delete line 13 `<link rel="stylesheet" href="src/css/Default.css"/>`. The css file `src/css/default.css` is named lowercase so not getting used/bundled here.

2017-12-10 20:03 UTC, evanharmon commented
It looks like in `public/index.html` on october 4th and 13th you added two `<script />` elements inside the `<body> </body>`.  You can delete line 25 as it is not doing anything. Line 26 is actually grabbing your `bundle.js` from your github public repo on load. Line 26 is needed for your site to function.

2017-12-10 20:04 UTC, evanharmon commented
here is a comment from my `index.html` in my hss-headspace create-react-app. 
```
    <!--
      Notice the use of %PUBLIC_URL% in the tags above.
      It will be replaced with the URL of the `public` folder during the build.
      Only files inside the `public` folder can be referenced from the HTML.

      Unlike "/favicon.ico" or "favicon.ico", "%PUBLIC_URL%/favicon.ico" will
      work correctly both with client-side routing and a non-root public URL.
      Learn how to configure a non-root public URL by running `npm run build`.
    -->
```

2017-12-10 20:05 UTC, evanharmon requested changes
Please make changes and submit new comments under this branch. It'll be added to the PR and i'll re-review. :)

2017-12-10 20:05 UTC, evanharmon commented on src/App.js
> +          <div className="portfolioItem">
The `<img />` element needs to be removed. The div has the background of the image in CSS and that loads correctly at `background-size: 150px;`

2017-12-10 20:05 UTC, evanharmon commented on src/App.js
> +              src={portfolioItem.png}
this is an incorrect reference to an import. The import is named `portfolioItem`. It would be `src={portfolioItem}`. No change needed as this element is going to be deleted.

2017-12-10 20:05 UTC, evanharmon commented on src/App.js
> +              src={portfolioItem.png}
locally this came up in chrome as an empty image icon bc of the import issue.

2017-12-10 20:05 UTC, evanharmon commented on src/App.js
> +import portfolioItem from './assets/portfolioItem.png';
This imported isn't needed. The picture is getting imported in your `App.css` file and bundled together in webpack

2017-12-11 20:36 UTC, laurelherting commented on src/App.js
> +import portfolioItem from './assets/portfolioItem.png';
ok, that makes sense.

2017-12-11 20:37 UTC, laurelherting commented on src/App.js
> +          <div className="portfolioItem">
Yes, I see now why it can be removed.

2017-12-11 20:37 UTC, laurelherting commented on src/App.js
> +              src={portfolioItem.png}
Good catch-I see where I went wrong here. I'll delete the element.

2017-12-11 20:49 UTC, evanharmon commented on public/index.html
> +    <!--
nice touch 😄

2017-12-11 20:51 UTC, evanharmon approved these changes
I approve this message.

2017-12-11 20:52 UTC, merged